### ISSUE TITLE
Could this be a typo in the code?

### ISSUE THREAD

**Issue by albep** [NumEconCopenhagen/ConsumptionSavingNotebooks#1]
Going over the code, I noted [this line](https://github.com/NumEconCopenhagen/ConsumptionSaving/blob/master/consav/upperenvelope.py#L104).

I understand we'd like to run the following `if` when, given an `ia`,  `m` is either within the interval `[m_vec[ia], m_vec[ia + 1]]` in the endogenous grid or `ia` is the second-to-last point in the grid, and `m` is greater than the last value in the endogenous grid `m_vec[Na - 1]`.

However, given that [this](https://github.com/NumEconCopenhagen/ConsumptionSaving/blob/master/consav/upperenvelope.py#L73) `for` loop goes up to `range(Na - 1)` i.e. `Na-2`, I think `extrap_above` will never be true and therefore there will never be extrapolation.

**Comment by JeppeDruedahl** [comment]
Thanks! You are completely right, it should be `Na-2` as you suggest. It has been changed now.
